Repository exercism/elixir-analyzer, pull requests merged in 2021-11, with the labels that each got.

#204 Add basic New Passport analysis
  config/config.exs
  lib/elixir_analyzer/constants.ex
  lib/elixir_analyzer/test_suite/new_passport.ex
  test/elixir_analyzer/test_suite/new_passport_test.exs
Labels: hacktoberfest-accepted

#215 Modify `check_source` to take a `%Source{}` argument instead of a string
  docs/recipes.md
  lib/elixir_analyzer/exercise_test.ex
  lib/elixir_analyzer/exercise_test/check_source/compiler.ex
  lib/elixir_analyzer/test_suite/german_sysadmin.ex
  test/support/analyzer_verification/check_source.ex
  test/support/analyzer_verification/suppress_if.ex
Labels: x:action/improve, x:type/docs, x:size/small

#219 Common check: function capture instead of defining a new anonymous function
  lib/elixir_analyzer/constants.ex
  lib/elixir_analyzer/exercise_test/common_checks.ex
  lib/elixir_analyzer/exercise_test/common_checks/function_capture.ex
  lib/elixir_analyzer/test_suite/top_secret.ex
  test/elixir_analyzer/exercise_test/common_checks/function_capture_test.exs
  test/elixir_analyzer/exercise_test/common_checks_test.exs
  test/elixir_analyzer/test_suite/bird_count_test.exs
  test/elixir_analyzer/test_suite/list_ops_test.exs
  test/elixir_analyzer/test_suite/top_secret_test.exs
Labels: x:module/analyzer, x:type/coding, x:size/medium

#232 Remove `top-secret` function capture comment
  lib/elixir_analyzer/constants.ex
Labels: x:action/fix, bug 🐛

#233 🤖 Update `.dockerignore` file
  .dockerignore
Labels: x:size/tiny
