Repository exercism/elixir-analyzer, pull requests merged in 2022-03, with the labels that each got.

#264 🤖 Rename Docker workflow
  .github/workflows/deploy.yml
Labels: x:size/tiny

#266 Running smoke tests in docker
  .github/workflows/elixir_test.yml
  Dockerfile
  bin/check_files.sh
  bin/run-tests-in-docker.sh
  bin/smoke_test.sh
  test_data/clock/perfect_solution/.meta/config.json
  test_data/clock/perfect_solution/expected_analysis.json
  test_data/clock/perfect_solution/lib/clock.ex
  test_data/lasagna/deprecated_modules/expected_analysis.json
  test_data/lasagna/failing_solution/expected_analysis.json
  test_data/lasagna/missing_config/expected_analysis.json
  test_data/lasagna/missing_exemplar/expected_analysis.json
  test_data/lasagna/perfect_solution/expected_analysis.json
  test_data/lasagna/wrong_config/expected_analysis.json
  test_data/lasagna/wrong_config2/expected_analysis.json
  test_data/lasagna/wrong_exemplar/expected_analysis.json
  test_data/two_fer/error_solution/expected_analysis.json
  test_data/two_fer/imperfect_solution/expected_analysis.json
  test_data/two_fer/informative_comments/expected_analysis.json
  test_data/two_fer/missing_example_solution/expected_analysis.json
  test_data/two_fer/missing_file_solution/expected_analysis.json
  test_data/two_fer/perfect_solution/expected_analysis.json
Labels: x:module/analyzer, x:type/ci, x:size/medium

#271 Do not delete `expected_analysis.json` during tests
  test/elixir_analyzer/cli_test.exs
Labels: x:size/tiny, bug 🐛
